### PR TITLE
Improvement for private repos implementation

### PR DESCRIPTION
**Pull request by Sliim**
This change allow using the token for all github requests if
`helm-github-stars-token` is non-nil.

User's private repositories will be fetched if this option is provided.

### CODE REVIEW

**Comment by Sliim** [comment]
Can you check your private repos are correctly added to the repos list please?
I think it's a better way to manipulate token, and using it for all requests provide a higher rate-limit.

Feel free to improve the code!

**Comment by xuchunyang** [comment]
If the token is provided we should use:
- https://api.github.com/user/repos to fetch all repos (including private repos)
- https://api.github.com/user/starred to fetch starred repos

if (only) the username is provided, we should use:
- https://api.github.com/users/_username_/repos
- https://api.github.com/users/_username_/starred

**Comment by xuchunyang** [comment]
> Can you check your private repos are correctly added to the repos list please?

I have pushed one more commit to my PR, everything should be ok (by using the token, I can confirm that private repos can also be fetched.)

> I think it's a better way to manipulate token, and using it for all requests provide a higher rate-limit.

Yes, it is, but I think 60 requests per hour is enough in most cases. If you worry about this, https://developer.github.com/guides/getting-started/#conditional-requests maybe worth taking a look.

Actually, let user refetch manually is not convenient at all. We can try to set cache expiration to refetch cache automatically.

**Comment by Sliim** [comment]
Hmm ok, I have ~1800 stars on github that generate ~20 requests.. I thank it was a good idea to use token if provided because after 3 call of `helm-github-stars-fetch` I'm blocked..

**Pull request closed without merging**
